# Generated by Django 3.1.5 on 2021-02-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='test_app.publication')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_in_crores', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporterBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('no_of_articles_written', models.PositiveIntegerField(default=0)),
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.reporter')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.FloatField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.publication')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='sponsors',
            field=models.ManyToManyField(through='test_app.PublicationSponsor', to='test_app.Sponsor'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(related_name='articles', to='test_app.Publication')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.reporter')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
